export const PERMISOS = {
  COMPANIAS_VER: 'companias.ver',
  COMPANIAS_CREAR: 'companias.crear',
  COMPANIAS_EDITAR: 'companias.editar',
  GRANJAS_VER: 'granjas.ver',
  GRANJAS_CREAR: 'granjas.crear',
  GRANJAS_EDITAR: 'granjas.editar',
  MAESTRAS_ADMINISTRAR: 'maestras.administrar',
  USUARIOS_VER: 'usuarios.ver',
  USUARIOS_CREAR: 'usuarios.crear',
  USUARIOS_EDITAR: 'usuarios.editar',
  PERFILES_ADMINISTRAR: 'perfiles.administrar',
  LOTES_VER: 'lotes.ver',
  LOTES_CREAR: 'lotes.crear',
  LOTES_EDITAR: 'lotes.editar',
  INVENTARIO_VER: 'inventario.ver',
  INVENTARIO_ALIMENTOS_CREAR: 'inventario.alimentos.crear',
  INVENTARIO_ALIMENTOS_EDITAR: 'inventario.alimentos.editar',
  INVENTARIO_PROVEEDORES_ADMINISTRAR: 'inventario.proveedores.administrar',
  INVENTARIO_ALMACENES_ADMINISTRAR: 'inventario.almacenes.administrar',
  INVENTARIO_MOVIMIENTOS_CREAR: 'inventario.movimientos.crear',
  INVENTARIO_AJUSTES_CREAR: 'inventario.ajustes.crear',
} as const;

export type PermisoCodigo = (typeof PERMISOS)[keyof typeof PERMISOS];
