export const PERMISOS = {
  COMPANIAS_VER: 'companias.ver',
  COMPANIAS_CREAR: 'companias.crear',
  COMPANIAS_EDITAR: 'companias.editar',
  GRANJAS_VER: 'granjas.ver',
  GRANJAS_CREAR: 'granjas.crear',
  GRANJAS_EDITAR: 'granjas.editar',
  MAESTRAS_ADMINISTRAR: 'maestras.administrar',
  USUARIOS_VER: 'usuarios.ver',
  USUARIOS_CREAR: 'usuarios.crear',
  USUARIOS_EDITAR: 'usuarios.editar',
  PERFILES_ADMINISTRAR: 'perfiles.administrar',
  LOTES_VER: 'lotes.ver',
  LOTES_CREAR: 'lotes.crear',
  LOTES_EDITAR: 'lotes.editar',
  UBICACIONES_MOVIMIENTOS_VER: 'ubicaciones.movimientos.ver',
  UBICACIONES_MOVIMIENTOS_CREAR: 'ubicaciones.movimientos.crear',
  UBICACIONES_MOVIMIENTOS_ANULAR: 'ubicaciones.movimientos.anular',
  INVENTARIO_VER: 'inventario.ver',
  INVENTARIO_ALIMENTOS_CREAR: 'inventario.alimentos.crear',
  INVENTARIO_ALIMENTOS_EDITAR: 'inventario.alimentos.editar',
  INVENTARIO_PROVEEDORES_ADMINISTRAR: 'inventario.proveedores.administrar',
  INVENTARIO_ALMACENES_ADMINISTRAR: 'inventario.almacenes.administrar',
  INVENTARIO_MOVIMIENTOS_CREAR: 'inventario.movimientos.crear',
  INVENTARIO_AJUSTES_CREAR: 'inventario.ajustes.crear',
  ALIMENTACION_CONSUMO_VER: 'alimentacion.consumo.ver',
  ALIMENTACION_CONSUMO_CREAR: 'alimentacion.consumo.crear',
  ALIMENTACION_CONSUMO_ANULAR: 'alimentacion.consumo.anular',
  ENGORDE_VER: 'engorde.ver',
  ENGORDE_INICIAR: 'engorde.iniciar',
  ENGORDE_BAJAS_CREAR: 'engorde.bajas.crear',
  ENGORDE_CERRAR: 'engorde.cerrar',
  ENGORDE_ANULAR: 'engorde.anular',
  PESOS_VER: 'pesos.ver',
  PESOS_CREAR: 'pesos.crear',
  PESOS_ANULAR: 'pesos.anular',
  REPORTES_ALIMENTACION_VER: 'reportes.alimentacion.ver',
  REPORTES_ENGORDE_VER: 'reportes.engorde.ver',
} as const;

export type PermisoCodigo = (typeof PERMISOS)[keyof typeof PERMISOS];
