export { Compania, Granja } from './organizacion.entities';
export {
  Perfil,
  PerfilPermiso,
  Permiso,
  Session,
  Usuario,
  UsuarioGranja,
  UsuarioPerfil,
} from './seguridad.entities';
export {
  FinalidadProductiva,
  MetodoPesaje,
  MotivoBajaEngorde,
  MotivoCierreEngorde,
  MotivoMovimientoUbicacion,
  PresentacionAlimento,
  Raza,
  TipoAlimento,
  TipoAnimal,
  TipoControlPeso,
  TipoMovimientoInventario,
  TipoUbicacion,
  Ubicacion,
  UnidadMedida,
} from './maestras.entities';
export {
  Alimento,
  Almacen,
  BajaEngorde,
  CierreEngorde,
  ConsumoAlimento,
  ControlPeso,
  EngordeLote,
  Lote,
  MovimientoInventario,
  MovimientoUbicacion,
  Proveedor,
} from './operacion.entities';
export { FeedbackRecomendacion, Recomendacion } from './asistente.entities';
export type { HipotesisRecomendacion } from './asistente.entities';

import { Compania, Granja } from './organizacion.entities';
import {
  Perfil,
  PerfilPermiso,
  Permiso,
  Session,
  Usuario,
  UsuarioGranja,
  UsuarioPerfil,
} from './seguridad.entities';
import {
  FinalidadProductiva,
  MetodoPesaje,
  MotivoBajaEngorde,
  MotivoCierreEngorde,
  MotivoMovimientoUbicacion,
  PresentacionAlimento,
  Raza,
  TipoAlimento,
  TipoAnimal,
  TipoControlPeso,
  TipoMovimientoInventario,
  TipoUbicacion,
  Ubicacion,
  UnidadMedida,
} from './maestras.entities';
import {
  Alimento,
  Almacen,
  BajaEngorde,
  CierreEngorde,
  ConsumoAlimento,
  ControlPeso,
  EngordeLote,
  Lote,
  MovimientoInventario,
  MovimientoUbicacion,
  Proveedor,
} from './operacion.entities';
import { FeedbackRecomendacion, Recomendacion } from './asistente.entities';

export const entities = [
  Compania,
  Granja,
  Usuario,
  Perfil,
  Permiso,
  PerfilPermiso,
  UsuarioPerfil,
  UsuarioGranja,
  Session,
  UnidadMedida,
  TipoMovimientoInventario,
  TipoControlPeso,
  TipoAnimal,
  Raza,
  FinalidadProductiva,
  TipoUbicacion,
  TipoAlimento,
  PresentacionAlimento,
  MotivoMovimientoUbicacion,
  MotivoCierreEngorde,
  MotivoBajaEngorde,
  MetodoPesaje,
  Ubicacion,
  Lote,
  MovimientoUbicacion,
  Alimento,
  Proveedor,
  Almacen,
  MovimientoInventario,
  ConsumoAlimento,
  EngordeLote,
  CierreEngorde,
  BajaEngorde,
  ControlPeso,
  Recomendacion,
  FeedbackRecomendacion,
];
