import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781471441714 implements MigrationInterface {
    name = 'InitialSchema1781471441714'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."companias_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "companias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying NOT NULL, "identificacionFiscal" character varying, "telefono" character varying, "correo" character varying, "direccion" character varying, "estadoRegistro" "public"."companias_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_54282f6c1e388971eb9a08d90ec" UNIQUE ("nombre"), CONSTRAINT "PK_cc197e9243dc92f088f18d2bfbf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."granjas_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "granjas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "codigo" character varying, "direccion" character varying, "estadoRegistro" "public"."granjas_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_a7ed3a3bba8567bd9fa7b841863" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_399b890565ec6a877d871587ef3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_estado_enum" AS ENUM('ACTIVO', 'INACTIVO', 'BLOQUEADO')`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "apellido" character varying, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "estado" "public"."usuarios_estado_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."perfiles_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "perfiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."perfiles_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f6e0251844d775210431c20c874" UNIQUE ("nombre"), CONSTRAINT "PK_50d8a0a9bdea75489c5f230ce27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permisos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "nombre" character varying NOT NULL, "modulo" character varying NOT NULL, "accion" character varying NOT NULL, "descripcion" character varying, CONSTRAINT "UQ_40d964f2742b2f4e3f379d3f460" UNIQUE ("codigo"), CONSTRAINT "PK_3127bd9cfeb13ae76186d0d9b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "perfil_permisos" ("perfilId" uuid NOT NULL, "permisoId" uuid NOT NULL, CONSTRAINT "PK_d9330bcbb470a43b59314073e19" PRIMARY KEY ("perfilId", "permisoId"))`);
        await queryRunner.query(`CREATE TABLE "usuario_perfiles" ("usuarioId" uuid NOT NULL, "perfilId" uuid NOT NULL, CONSTRAINT "PK_f2aaecd94a96bd2d07c6d7a4279" PRIMARY KEY ("usuarioId", "perfilId"))`);
        await queryRunner.query(`CREATE TABLE "usuario_granjas" ("usuarioId" uuid NOT NULL, "granjaId" uuid NOT NULL, CONSTRAINT "PK_9090f713bc8b4d979b127df1347" PRIMARY KEY ("usuarioId", "granjaId"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionToken" character varying NOT NULL, "userId" uuid NOT NULL, "expires" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_8b5e2ec52e335c0fe16d7ec3584" UNIQUE ("sessionToken"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."unidades_medida_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "unidades_medida" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "nombre" character varying NOT NULL, "abreviatura" character varying NOT NULL, "estadoRegistro" "public"."unidades_medida_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', CONSTRAINT "UQ_d97cb04b559197c7009e0f8903c" UNIQUE ("codigo"), CONSTRAINT "PK_b299f0e6758c0c02ae3e729232a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_movimiento_inventario_signo_enum" AS ENUM('ENTRADA', 'SALIDA')`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_movimiento_inventario_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "tipos_movimiento_inventario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "nombre" character varying NOT NULL, "signo" "public"."tipos_movimiento_inventario_signo_enum" NOT NULL, "esAjuste" boolean NOT NULL DEFAULT false, "estadoRegistro" "public"."tipos_movimiento_inventario_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', CONSTRAINT "UQ_072d8825941b6fe3a1011224a43" UNIQUE ("codigo"), CONSTRAINT "PK_c7a19995c1e8166e672598b2fe8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_control_peso_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "tipos_control_peso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "nombre" character varying NOT NULL, "estadoRegistro" "public"."tipos_control_peso_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', CONSTRAINT "UQ_c6210447f38aef10182e85480d0" UNIQUE ("codigo"), CONSTRAINT "PK_79d36de8559dd4cd3cd458e338b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_animal_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "tipos_animal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "requiereRaza" boolean NOT NULL DEFAULT false, "duracionGestacionDias" integer, "estadoRegistro" "public"."tipos_animal_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f0fb55f7ffeeb0cb39c6796596a" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_61f21bb0ce4c7ea7e489ab7a95c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."razas_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "razas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "tipoAnimalId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."razas_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cb9760d1995081420c2809e40e9" UNIQUE ("tipoAnimalId", "nombre"), CONSTRAINT "PK_02b0999e0c7e8e2604f13d74d8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."finalidades_productivas_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "finalidades_productivas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."finalidades_productivas_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_44207970f93441cc861a70c821c" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_e83572e1ca60ace07617a9066d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_ubicacion_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "tipos_ubicacion" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."tipos_ubicacion_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6074e57d954e59d0fc359f04bb0" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_ac4b64a5f86a062984df6fedded" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_alimento_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "tipos_alimento" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."tipos_alimento_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_98c210dfa9b3f7b0143f83c8ca8" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_990c85566029dbf03fc2156c611" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."presentaciones_alimento_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "presentaciones_alimento" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."presentaciones_alimento_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6456fd7d46da0538423edb03eb4" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_3846157f7d5c306a765f311cc7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."motivos_movimiento_ubicacion_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "motivos_movimiento_ubicacion" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."motivos_movimiento_ubicacion_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5b94ac7e9fb90818738138fe1ae" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_bec45f64783774be008ddea229b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."motivos_cierre_engorde_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "motivos_cierre_engorde" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."motivos_cierre_engorde_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_57c28e40bb107ea3909781699cd" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_66b011924867d539ad6c604c8c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."motivos_baja_engorde_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "motivos_baja_engorde" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."motivos_baja_engorde_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6ee06ebb5945bee188bc8a2a5b8" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_bc0f81dd14546df1961ebc5dcd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."metodos_pesaje_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "metodos_pesaje" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "estadoRegistro" "public"."metodos_pesaje_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_11a036a9b78cd589995ac40b3ed" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_0df4d990242e4b8460b8f8121d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ubicaciones_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "ubicaciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "granjaId" uuid NOT NULL, "tipoUbicacionId" uuid NOT NULL, "nombre" character varying NOT NULL, "codigo" character varying, "descripcion" character varying, "estadoRegistro" "public"."ubicaciones_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_00252b1cabf706465eef9e29027" UNIQUE ("granjaId", "nombre"), CONSTRAINT "PK_a9ce0b671142b83ebff02722cf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lotes_estadooperativo_enum" AS ENUM('ACTIVO', 'CERRADO', 'CANCELADO')`);
        await queryRunner.query(`CREATE TYPE "public"."lotes_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "lotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "codigo" character varying NOT NULL, "tipoAnimalId" uuid NOT NULL, "finalidadProductivaId" uuid NOT NULL, "fechaInicio" date NOT NULL, "cantidadInicial" integer NOT NULL, "ubicacionId" uuid, "estadoOperativo" "public"."lotes_estadooperativo_enum" NOT NULL DEFAULT 'ACTIVO', "observaciones" character varying, "estadoRegistro" "public"."lotes_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_5b45088fd249654aa7e7dc6c474" UNIQUE ("granjaId", "codigo"), CONSTRAINT "PK_6eda564423c09706b95cbf8ae1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movimientos_ubicacion" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "loteId" uuid NOT NULL, "ubicacionOrigenId" uuid, "ubicacionDestinoId" uuid NOT NULL, "motivoId" uuid, "fecha" date NOT NULL, "observaciones" character varying, "anulado" boolean NOT NULL DEFAULT false, "anuladoAt" TIMESTAMP WITH TIME ZONE, "anuladoById" character varying, "motivoAnulacion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, CONSTRAINT "PK_5f4a58a8e9884f5fd8e4dc1278f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."alimentos_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "alimentos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "tipoAlimentoId" uuid NOT NULL, "presentacionId" uuid NOT NULL, "unidadMedidaId" uuid NOT NULL, "factorConversion" numeric(12,4) NOT NULL DEFAULT '1', "costoReferencia" numeric(12,4), "observaciones" character varying, "estadoRegistro" "public"."alimentos_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_db9c2c49be463d9415052d26a76" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_da5d1df2a12881071a1c6cf367d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."proveedores_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "proveedores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "nombre" character varying NOT NULL, "identificacionFiscal" character varying, "telefono" character varying, "correo" character varying, "direccion" character varying, "estadoRegistro" "public"."proveedores_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_e20ca2d6bcb5532d6b680b6f3c6" UNIQUE ("companiaId", "nombre"), CONSTRAINT "PK_1dcf121f19f362fb1b4c0a493a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."almacenes_estadoregistro_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "almacenes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "nombre" character varying NOT NULL, "codigo" character varying, "ubicacionId" uuid, "observaciones" character varying, "estadoRegistro" "public"."almacenes_estadoregistro_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying, "updatedById" character varying, CONSTRAINT "UQ_d830e47ea43a0ea5a75dc20111f" UNIQUE ("granjaId", "nombre"), CONSTRAINT "PK_2af9818dc2019bc97c7d26217e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movimientos_inventario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "almacenId" uuid NOT NULL, "alimentoId" uuid NOT NULL, "tipoMovimientoId" uuid NOT NULL, "fecha" date NOT NULL, "cantidad" numeric(12,4) NOT NULL, "unidadMedidaId" uuid NOT NULL, "costoUnitario" numeric(12,4), "costoTotal" numeric(12,4), "proveedorId" uuid, "referencia" character varying, "motivoAjuste" character varying, "observaciones" character varying, "anulado" boolean NOT NULL DEFAULT false, "anuladoAt" TIMESTAMP WITH TIME ZONE, "anuladoById" character varying, "motivoAnulacion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, CONSTRAINT "PK_812f6e4f95b017981363c4b9ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consumos_alimento" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "loteId" uuid NOT NULL, "alimentoId" uuid NOT NULL, "almacenId" uuid NOT NULL, "movimientoInventarioId" uuid NOT NULL, "fecha" date NOT NULL, "cantidad" numeric(12,4) NOT NULL, "unidadMedidaId" uuid NOT NULL, "observaciones" character varying, "anulado" boolean NOT NULL DEFAULT false, "anuladoAt" TIMESTAMP WITH TIME ZONE, "anuladoById" character varying, "motivoAnulacion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, CONSTRAINT "UQ_54d0c9c1939bb34999dacfcfd65" UNIQUE ("movimientoInventarioId"), CONSTRAINT "REL_54d0c9c1939bb34999dacfcfd6" UNIQUE ("movimientoInventarioId"), CONSTRAINT "PK_26b2e62a2d0e8eaef49820ad580" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."engordes_lote_estado_enum" AS ENUM('EN_CURSO', 'CERRADO', 'ANULADO')`);
        await queryRunner.query(`CREATE TABLE "engordes_lote" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "loteId" uuid NOT NULL, "fechaInicio" date NOT NULL, "cantidadInicial" integer NOT NULL, "pesoInicialPromedio" numeric(10,3), "objetivoPeso" numeric(10,3), "fechaCierre" date, "cantidadFinal" integer, "pesoFinalPromedio" numeric(10,3), "motivoCierreId" uuid, "observaciones" character varying, "estado" "public"."engordes_lote_estado_enum" NOT NULL DEFAULT 'EN_CURSO', "anulado" boolean NOT NULL DEFAULT false, "anuladoAt" TIMESTAMP WITH TIME ZONE, "anuladoById" character varying, "motivoAnulacion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, CONSTRAINT "PK_e4313043abbf4f1c03c4924807b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bajas_engorde" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "engordeId" uuid NOT NULL, "loteId" uuid NOT NULL, "motivoId" uuid, "fecha" date NOT NULL, "cantidad" integer NOT NULL, "observaciones" character varying, "anulado" boolean NOT NULL DEFAULT false, "anuladoAt" TIMESTAMP WITH TIME ZONE, "anuladoById" character varying, "motivoAnulacion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, CONSTRAINT "PK_306f7f5a6b520c93bfcf1f17213" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "controles_peso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companiaId" uuid NOT NULL, "granjaId" uuid NOT NULL, "loteId" uuid NOT NULL, "engordeId" uuid, "tipoControlId" uuid NOT NULL, "metodoPesajeId" uuid, "fecha" date NOT NULL, "peso" numeric(10,3) NOT NULL, "unidadMedidaId" uuid NOT NULL, "cantidadMuestra" integer, "observaciones" character varying, "anulado" boolean NOT NULL DEFAULT false, "anuladoAt" TIMESTAMP WITH TIME ZONE, "anuladoById" character varying, "motivoAnulacion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, CONSTRAINT "PK_14464a19c0c9ecf036197a32d76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "granjas" ADD CONSTRAINT "FK_58f096f78a0174859fbfbff007b" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_645ec387334541b9aedb8229354" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfil_permisos" ADD CONSTRAINT "FK_03cf27e18fe663dab69ae15aec4" FOREIGN KEY ("perfilId") REFERENCES "perfiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfil_permisos" ADD CONSTRAINT "FK_39fa3ad257a77015be0e79de427" FOREIGN KEY ("permisoId") REFERENCES "permisos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_perfiles" ADD CONSTRAINT "FK_99fab34d1047b2828739804d412" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_perfiles" ADD CONSTRAINT "FK_27a6ecbafc68bf2fe65115aec0c" FOREIGN KEY ("perfilId") REFERENCES "perfiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_granjas" ADD CONSTRAINT "FK_ffbb28188924d6733fcc4de5cb1" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_granjas" ADD CONSTRAINT "FK_a1a0f66b96930235adfa8a4e4a2" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_animal" ADD CONSTRAINT "FK_6cd1d27d8858b303f6c4b2cc17a" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "razas" ADD CONSTRAINT "FK_f6a1e8a22df3659045103799092" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "razas" ADD CONSTRAINT "FK_9c407e29ea9c62ac68d50309dbe" FOREIGN KEY ("tipoAnimalId") REFERENCES "tipos_animal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finalidades_productivas" ADD CONSTRAINT "FK_ef31434e3ada4dfd4f08bcf390a" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_ubicacion" ADD CONSTRAINT "FK_4c55b4e63ecb3b52f9994b7b595" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_alimento" ADD CONSTRAINT "FK_e0176349ba087c791ea7a31383d" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presentaciones_alimento" ADD CONSTRAINT "FK_23ad7b111e9c8dc9b3c73edb050" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "motivos_movimiento_ubicacion" ADD CONSTRAINT "FK_40dbb9a9c3aa6b670d7b8c7282d" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "motivos_cierre_engorde" ADD CONSTRAINT "FK_93f7c2ea895b7e8e3c37e531e57" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "motivos_baja_engorde" ADD CONSTRAINT "FK_29f1f8a4e5943890b216a3d2b21" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metodos_pesaje" ADD CONSTRAINT "FK_241faa85cd7b2bc12ec076e71b9" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ubicaciones" ADD CONSTRAINT "FK_bd59204844d6812ec3098ca0b10" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ubicaciones" ADD CONSTRAINT "FK_2b1a2054319c7af9de1c444e918" FOREIGN KEY ("tipoUbicacionId") REFERENCES "tipos_ubicacion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_6ca663be2109e72388c37e7e737" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_d0c7cba773c4d4474b90b2057de" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_97cdfa9a8abdcb58a199a7aa2d9" FOREIGN KEY ("tipoAnimalId") REFERENCES "tipos_animal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_487ddfa1622af93646428ef3b50" FOREIGN KEY ("finalidadProductivaId") REFERENCES "finalidades_productivas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_c8628051cd9ae1d6d75dc9cc11b" FOREIGN KEY ("ubicacionId") REFERENCES "ubicaciones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" ADD CONSTRAINT "FK_5d28d9129d2f288ad91f8d36fc5" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" ADD CONSTRAINT "FK_cf834bb189b4086d4a0994c7fe9" FOREIGN KEY ("loteId") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" ADD CONSTRAINT "FK_c9215b1bdc72f432049f9d50861" FOREIGN KEY ("ubicacionOrigenId") REFERENCES "ubicaciones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" ADD CONSTRAINT "FK_f88286b954cb538c1cbc2acb2fb" FOREIGN KEY ("ubicacionDestinoId") REFERENCES "ubicaciones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" ADD CONSTRAINT "FK_2278c01ad22a6ca5f2de0407a89" FOREIGN KEY ("motivoId") REFERENCES "motivos_movimiento_ubicacion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentos" ADD CONSTRAINT "FK_d5a7617a119316d4b7b51ff645e" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentos" ADD CONSTRAINT "FK_fd21aee5e611d748238effbd957" FOREIGN KEY ("tipoAlimentoId") REFERENCES "tipos_alimento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentos" ADD CONSTRAINT "FK_f2effb61e0cbc801dfa94d1d19e" FOREIGN KEY ("presentacionId") REFERENCES "presentaciones_alimento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentos" ADD CONSTRAINT "FK_b5961d9f340e7ed3b2b68332fb4" FOREIGN KEY ("unidadMedidaId") REFERENCES "unidades_medida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proveedores" ADD CONSTRAINT "FK_9e8226e799f6258b8e68efe3083" FOREIGN KEY ("companiaId") REFERENCES "companias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "almacenes" ADD CONSTRAINT "FK_19daa5212f9c58bfaa7b410c474" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "almacenes" ADD CONSTRAINT "FK_56af082f2764c90f945d8027ba5" FOREIGN KEY ("ubicacionId") REFERENCES "ubicaciones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_95e09009f30bb28f5e9c4eb5612" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_9819e9ad5e9d1a80a1d875e061b" FOREIGN KEY ("almacenId") REFERENCES "almacenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_3f4742bd62e707fe835236e10c4" FOREIGN KEY ("alimentoId") REFERENCES "alimentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_5f36062f6dc4513913269380c98" FOREIGN KEY ("tipoMovimientoId") REFERENCES "tipos_movimiento_inventario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_a5e68800e13a390d374abe9fdfa" FOREIGN KEY ("unidadMedidaId") REFERENCES "unidades_medida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_2bb1b847524ee608623272c6d3a" FOREIGN KEY ("proveedorId") REFERENCES "proveedores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" ADD CONSTRAINT "FK_0938750c707093d1226905f7143" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" ADD CONSTRAINT "FK_c75d8617180ee90a226c46e81f4" FOREIGN KEY ("loteId") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" ADD CONSTRAINT "FK_4bb8f0d8225810b2f7e343b85e3" FOREIGN KEY ("alimentoId") REFERENCES "alimentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" ADD CONSTRAINT "FK_3d70cc30ffce835d7d7b2296759" FOREIGN KEY ("almacenId") REFERENCES "almacenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" ADD CONSTRAINT "FK_54d0c9c1939bb34999dacfcfd65" FOREIGN KEY ("movimientoInventarioId") REFERENCES "movimientos_inventario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" ADD CONSTRAINT "FK_18b635f657016603cc80f7b7abe" FOREIGN KEY ("unidadMedidaId") REFERENCES "unidades_medida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engordes_lote" ADD CONSTRAINT "FK_85de8a1cf76716dd1b5eb1789c6" FOREIGN KEY ("loteId") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engordes_lote" ADD CONSTRAINT "FK_a2d970eb4d33eeb8714bbd547a3" FOREIGN KEY ("motivoCierreId") REFERENCES "motivos_cierre_engorde"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bajas_engorde" ADD CONSTRAINT "FK_90668bd677c61eb89778544f5aa" FOREIGN KEY ("engordeId") REFERENCES "engordes_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bajas_engorde" ADD CONSTRAINT "FK_f660bc77d0c7671ff3072e79345" FOREIGN KEY ("motivoId") REFERENCES "motivos_baja_engorde"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controles_peso" ADD CONSTRAINT "FK_b7aec69fa4ec4264534322d761b" FOREIGN KEY ("granjaId") REFERENCES "granjas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controles_peso" ADD CONSTRAINT "FK_aa105244aa806e6b2e7daea2dfa" FOREIGN KEY ("loteId") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controles_peso" ADD CONSTRAINT "FK_7017c1f9ba9ad07bf5d5c97e169" FOREIGN KEY ("engordeId") REFERENCES "engordes_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controles_peso" ADD CONSTRAINT "FK_14b053796f3fdab1d57218d1be4" FOREIGN KEY ("tipoControlId") REFERENCES "tipos_control_peso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controles_peso" ADD CONSTRAINT "FK_2257b42572f28d70eac3f0a5b11" FOREIGN KEY ("metodoPesajeId") REFERENCES "metodos_pesaje"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controles_peso" ADD CONSTRAINT "FK_572cdba6fd7bf3fbe070164d546" FOREIGN KEY ("unidadMedidaId") REFERENCES "unidades_medida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "controles_peso" DROP CONSTRAINT "FK_572cdba6fd7bf3fbe070164d546"`);
        await queryRunner.query(`ALTER TABLE "controles_peso" DROP CONSTRAINT "FK_2257b42572f28d70eac3f0a5b11"`);
        await queryRunner.query(`ALTER TABLE "controles_peso" DROP CONSTRAINT "FK_14b053796f3fdab1d57218d1be4"`);
        await queryRunner.query(`ALTER TABLE "controles_peso" DROP CONSTRAINT "FK_7017c1f9ba9ad07bf5d5c97e169"`);
        await queryRunner.query(`ALTER TABLE "controles_peso" DROP CONSTRAINT "FK_aa105244aa806e6b2e7daea2dfa"`);
        await queryRunner.query(`ALTER TABLE "controles_peso" DROP CONSTRAINT "FK_b7aec69fa4ec4264534322d761b"`);
        await queryRunner.query(`ALTER TABLE "bajas_engorde" DROP CONSTRAINT "FK_f660bc77d0c7671ff3072e79345"`);
        await queryRunner.query(`ALTER TABLE "bajas_engorde" DROP CONSTRAINT "FK_90668bd677c61eb89778544f5aa"`);
        await queryRunner.query(`ALTER TABLE "engordes_lote" DROP CONSTRAINT "FK_a2d970eb4d33eeb8714bbd547a3"`);
        await queryRunner.query(`ALTER TABLE "engordes_lote" DROP CONSTRAINT "FK_85de8a1cf76716dd1b5eb1789c6"`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" DROP CONSTRAINT "FK_18b635f657016603cc80f7b7abe"`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" DROP CONSTRAINT "FK_54d0c9c1939bb34999dacfcfd65"`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" DROP CONSTRAINT "FK_3d70cc30ffce835d7d7b2296759"`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" DROP CONSTRAINT "FK_4bb8f0d8225810b2f7e343b85e3"`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" DROP CONSTRAINT "FK_c75d8617180ee90a226c46e81f4"`);
        await queryRunner.query(`ALTER TABLE "consumos_alimento" DROP CONSTRAINT "FK_0938750c707093d1226905f7143"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_2bb1b847524ee608623272c6d3a"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_a5e68800e13a390d374abe9fdfa"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_5f36062f6dc4513913269380c98"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_3f4742bd62e707fe835236e10c4"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_9819e9ad5e9d1a80a1d875e061b"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_95e09009f30bb28f5e9c4eb5612"`);
        await queryRunner.query(`ALTER TABLE "almacenes" DROP CONSTRAINT "FK_56af082f2764c90f945d8027ba5"`);
        await queryRunner.query(`ALTER TABLE "almacenes" DROP CONSTRAINT "FK_19daa5212f9c58bfaa7b410c474"`);
        await queryRunner.query(`ALTER TABLE "proveedores" DROP CONSTRAINT "FK_9e8226e799f6258b8e68efe3083"`);
        await queryRunner.query(`ALTER TABLE "alimentos" DROP CONSTRAINT "FK_b5961d9f340e7ed3b2b68332fb4"`);
        await queryRunner.query(`ALTER TABLE "alimentos" DROP CONSTRAINT "FK_f2effb61e0cbc801dfa94d1d19e"`);
        await queryRunner.query(`ALTER TABLE "alimentos" DROP CONSTRAINT "FK_fd21aee5e611d748238effbd957"`);
        await queryRunner.query(`ALTER TABLE "alimentos" DROP CONSTRAINT "FK_d5a7617a119316d4b7b51ff645e"`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" DROP CONSTRAINT "FK_2278c01ad22a6ca5f2de0407a89"`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" DROP CONSTRAINT "FK_f88286b954cb538c1cbc2acb2fb"`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" DROP CONSTRAINT "FK_c9215b1bdc72f432049f9d50861"`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" DROP CONSTRAINT "FK_cf834bb189b4086d4a0994c7fe9"`);
        await queryRunner.query(`ALTER TABLE "movimientos_ubicacion" DROP CONSTRAINT "FK_5d28d9129d2f288ad91f8d36fc5"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_c8628051cd9ae1d6d75dc9cc11b"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_487ddfa1622af93646428ef3b50"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_97cdfa9a8abdcb58a199a7aa2d9"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_d0c7cba773c4d4474b90b2057de"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_6ca663be2109e72388c37e7e737"`);
        await queryRunner.query(`ALTER TABLE "ubicaciones" DROP CONSTRAINT "FK_2b1a2054319c7af9de1c444e918"`);
        await queryRunner.query(`ALTER TABLE "ubicaciones" DROP CONSTRAINT "FK_bd59204844d6812ec3098ca0b10"`);
        await queryRunner.query(`ALTER TABLE "metodos_pesaje" DROP CONSTRAINT "FK_241faa85cd7b2bc12ec076e71b9"`);
        await queryRunner.query(`ALTER TABLE "motivos_baja_engorde" DROP CONSTRAINT "FK_29f1f8a4e5943890b216a3d2b21"`);
        await queryRunner.query(`ALTER TABLE "motivos_cierre_engorde" DROP CONSTRAINT "FK_93f7c2ea895b7e8e3c37e531e57"`);
        await queryRunner.query(`ALTER TABLE "motivos_movimiento_ubicacion" DROP CONSTRAINT "FK_40dbb9a9c3aa6b670d7b8c7282d"`);
        await queryRunner.query(`ALTER TABLE "presentaciones_alimento" DROP CONSTRAINT "FK_23ad7b111e9c8dc9b3c73edb050"`);
        await queryRunner.query(`ALTER TABLE "tipos_alimento" DROP CONSTRAINT "FK_e0176349ba087c791ea7a31383d"`);
        await queryRunner.query(`ALTER TABLE "tipos_ubicacion" DROP CONSTRAINT "FK_4c55b4e63ecb3b52f9994b7b595"`);
        await queryRunner.query(`ALTER TABLE "finalidades_productivas" DROP CONSTRAINT "FK_ef31434e3ada4dfd4f08bcf390a"`);
        await queryRunner.query(`ALTER TABLE "razas" DROP CONSTRAINT "FK_9c407e29ea9c62ac68d50309dbe"`);
        await queryRunner.query(`ALTER TABLE "razas" DROP CONSTRAINT "FK_f6a1e8a22df3659045103799092"`);
        await queryRunner.query(`ALTER TABLE "tipos_animal" DROP CONSTRAINT "FK_6cd1d27d8858b303f6c4b2cc17a"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "usuario_granjas" DROP CONSTRAINT "FK_a1a0f66b96930235adfa8a4e4a2"`);
        await queryRunner.query(`ALTER TABLE "usuario_granjas" DROP CONSTRAINT "FK_ffbb28188924d6733fcc4de5cb1"`);
        await queryRunner.query(`ALTER TABLE "usuario_perfiles" DROP CONSTRAINT "FK_27a6ecbafc68bf2fe65115aec0c"`);
        await queryRunner.query(`ALTER TABLE "usuario_perfiles" DROP CONSTRAINT "FK_99fab34d1047b2828739804d412"`);
        await queryRunner.query(`ALTER TABLE "perfil_permisos" DROP CONSTRAINT "FK_39fa3ad257a77015be0e79de427"`);
        await queryRunner.query(`ALTER TABLE "perfil_permisos" DROP CONSTRAINT "FK_03cf27e18fe663dab69ae15aec4"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_645ec387334541b9aedb8229354"`);
        await queryRunner.query(`ALTER TABLE "granjas" DROP CONSTRAINT "FK_58f096f78a0174859fbfbff007b"`);
        await queryRunner.query(`DROP TABLE "controles_peso"`);
        await queryRunner.query(`DROP TABLE "bajas_engorde"`);
        await queryRunner.query(`DROP TABLE "engordes_lote"`);
        await queryRunner.query(`DROP TYPE "public"."engordes_lote_estado_enum"`);
        await queryRunner.query(`DROP TABLE "consumos_alimento"`);
        await queryRunner.query(`DROP TABLE "movimientos_inventario"`);
        await queryRunner.query(`DROP TABLE "almacenes"`);
        await queryRunner.query(`DROP TYPE "public"."almacenes_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "proveedores"`);
        await queryRunner.query(`DROP TYPE "public"."proveedores_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "alimentos"`);
        await queryRunner.query(`DROP TYPE "public"."alimentos_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "movimientos_ubicacion"`);
        await queryRunner.query(`DROP TABLE "lotes"`);
        await queryRunner.query(`DROP TYPE "public"."lotes_estadoregistro_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lotes_estadooperativo_enum"`);
        await queryRunner.query(`DROP TABLE "ubicaciones"`);
        await queryRunner.query(`DROP TYPE "public"."ubicaciones_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "metodos_pesaje"`);
        await queryRunner.query(`DROP TYPE "public"."metodos_pesaje_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "motivos_baja_engorde"`);
        await queryRunner.query(`DROP TYPE "public"."motivos_baja_engorde_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "motivos_cierre_engorde"`);
        await queryRunner.query(`DROP TYPE "public"."motivos_cierre_engorde_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "motivos_movimiento_ubicacion"`);
        await queryRunner.query(`DROP TYPE "public"."motivos_movimiento_ubicacion_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "presentaciones_alimento"`);
        await queryRunner.query(`DROP TYPE "public"."presentaciones_alimento_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "tipos_alimento"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_alimento_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "tipos_ubicacion"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_ubicacion_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "finalidades_productivas"`);
        await queryRunner.query(`DROP TYPE "public"."finalidades_productivas_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "razas"`);
        await queryRunner.query(`DROP TYPE "public"."razas_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "tipos_animal"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_animal_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "tipos_control_peso"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_control_peso_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "tipos_movimiento_inventario"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_movimiento_inventario_estadoregistro_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_movimiento_inventario_signo_enum"`);
        await queryRunner.query(`DROP TABLE "unidades_medida"`);
        await queryRunner.query(`DROP TYPE "public"."unidades_medida_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "usuario_granjas"`);
        await queryRunner.query(`DROP TABLE "usuario_perfiles"`);
        await queryRunner.query(`DROP TABLE "perfil_permisos"`);
        await queryRunner.query(`DROP TABLE "permisos"`);
        await queryRunner.query(`DROP TABLE "perfiles"`);
        await queryRunner.query(`DROP TYPE "public"."perfiles_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_estado_enum"`);
        await queryRunner.query(`DROP TABLE "granjas"`);
        await queryRunner.query(`DROP TYPE "public"."granjas_estadoregistro_enum"`);
        await queryRunner.query(`DROP TABLE "companias"`);
        await queryRunner.query(`DROP TYPE "public"."companias_estadoregistro_enum"`);
    }

}
